name: Production CI Pipeline
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
jobs:
  quality-gate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.10", "3.11"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest black flake8 mypy bandit safety coverage pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Security scan
      run: |
        bandit -r . -ll --exclude=./venv,./**/venv/**,./*venv*
        safety check
    
    - name: Format check
      run: |
        black --check --exclude=venv .

    - name: Lint check  
      run: |
        flake8 . --exclude=venv,tests --select=E722,F401,F821,E402 --max-line-length=88

    - name: Tests
      continue-on-error: true
      run: |
        pytest
